// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWe0c9JIAYWVZI7MQUiXctU3-pqFECgHw',
    appId: '1:925377137380:web:09c728bea7b147749ebaf1',
    messagingSenderId: '925377137380',
    projectId: 'love-days-bd683',
    authDomain: 'love-days-bd683.firebaseapp.com',
    storageBucket: 'love-days-bd683.firebasestorage.app',
    measurementId: 'G-9Y6MBZSRVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwjgsYuaIH5qqd2DqgNmjisuoRHgKYfP4',
    appId: '1:925377137380:android:11cce31727a9af0a9ebaf1',
    messagingSenderId: '925377137380',
    projectId: 'love-days-bd683',
    storageBucket: 'love-days-bd683.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh1xR5jrQTdi0wxrtUxM0RuqKCheMHbpA',
    appId: '1:925377137380:ios:abb234ec7274eb3b9ebaf1',
    messagingSenderId: '925377137380',
    projectId: 'love-days-bd683',
    storageBucket: 'love-days-bd683.firebasestorage.app',
    androidClientId: '925377137380-e34fojaqj2pbp7rj55h791csr4kmc62p.apps.googleusercontent.com',
    iosClientId: '925377137380-snhtj5rfd0egs074ruqn485ddqmjeopr.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveDays',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh1xR5jrQTdi0wxrtUxM0RuqKCheMHbpA',
    appId: '1:925377137380:ios:abb234ec7274eb3b9ebaf1',
    messagingSenderId: '925377137380',
    projectId: 'love-days-bd683',
    storageBucket: 'love-days-bd683.firebasestorage.app',
    androidClientId: '925377137380-e34fojaqj2pbp7rj55h791csr4kmc62p.apps.googleusercontent.com',
    iosClientId: '925377137380-snhtj5rfd0egs074ruqn485ddqmjeopr.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveDays',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWe0c9JIAYWVZI7MQUiXctU3-pqFECgHw',
    appId: '1:925377137380:web:49d7c15a529f459a9ebaf1',
    messagingSenderId: '925377137380',
    projectId: 'love-days-bd683',
    authDomain: 'love-days-bd683.firebaseapp.com',
    storageBucket: 'love-days-bd683.firebasestorage.app',
    measurementId: 'G-56KYV35R92',
  );

}